### ISSUE TITLE
Multilingual support and generating empty sheets?

### ISSUE THREAD

**Issue by drcxd** [matsavage/DND-5e-LaTeX-Character-Sheet-Template#38]
Hello,

I am trying to adapt this template for languages other than English. I found that if simply input Chinese characters to constructs, for example `CharacterName`, then the characters are simply rendered as squares. My current solution for this problem is:

```
\newfontfamily\cjkfont{KaiTi}
\CharacterName{\cjkfont{中文字符}}
```

This works but is a little cumbersome. Is there anyway I can make the Chinese characters automatically fallback to a certain font, so I do not have to specify it explicitly?

Another related problem is to generate empty sheets. I found links to empty sheets in the README, but they are in English. I would like to replace some of the text to Chinese. However, I found that if I left some of the constructs' input as nothing (`SetProficiency{}`), the compilation stops with the following error:

```
! LaTeX Error: Missing number before '/'.
l.33 ^^I\SetProficiency{}
```

How can I circumvent this problem and generate an empty sheet?

Any help is appreciated.

**Comment by matsavage** [comment]
Hi,

For issue 1:
I actually define a font which is used for all of the handwriting entry, I would suggest changing the font here and see if that works:
https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/blob/53f2b0baa54e237f7897e0157423a4bc8fe095e3/dndtemplate.sty#L9

I would imagine this issue is because the font I defined does not have any Chinese characters. 

Issue 2:
Am I right in thinking you want to make a sheet with the header text in Chinese, but no entries for the boxes in that case I would suggest commenting out the player-input.tex file(s) and these will no longer be required
https://github.com/matsavage/DND-5e-LaTeX-Character-Sheet-Template/blob/53f2b0baa54e237f7897e0157423a4bc8fe095e3/template/character-sheet.tex#L20

Hope these help, I made this a long time ago and am not an active user of it anymore. Feel free to get back in touch if they don’t work, or write a tutorial if you figure it out
